#!/bin/bash
dbserver='127.0.0.1'
dbuser='root'
dbpasswd='abc12321'
dbname='globe'
backtime=`date +%Y%m%d`
logpath='/usr/etc/mysql/'
datapath='/usr/etc/mysql/'

echo "################## ${backtime} #############################" 
echo "start mysql backup" 
#header
echo "" >> ${logpath}/mysqlback.log
echo "-------------------------------------------------" >> ${logpath}/mysqlback.log
echo "backup time: ${backtime},database: ${dbname} start..." >> ${logpath}/mysqlback.log
#backup start
for table in $dbname; do
source=`mysqldump -h ${dbserver} -u ${dbuser} -p${dbpasswd} ${table} > ${logpath}/${backtime}.sql` 2>> ${logpath}/mysqlback.log;
#success
if [ "$?" == 0 ];then
cd $datapath
#tar the backup file
tar zcf ${table}${backtime}.tar.gz ${backtime}.sql > /dev/null
#remove the original file and only save the tarball
rm -f ${datapath}/${backtime}.sql
#a week backup history
find $datapath -name "*.tar.gz" -type f -mtime +7 -exec rm -rf {} \; > /dev/null 2>&1
echo "database ${dbname} backup success!!" >> ${logpath}/mysqlback.log
else
#if the backup failed...then
echo "database ${dbname} backup failed!!" >> ${logpath}/mysqlback.log
fi
done
echo "finish the backup process."
echo "################## ${backtime} #############################"
